disabled_rules:
  - type_name
  - line_length
  - identifier_name
  - trailing_whitespace
  - unused_closure_parameter
  - nesting

excluded:
  - Pods
  - vendor
  - build

force_cast: warning
force_try: warning
function_body_length: 
  error: 150
type_body_length:
  error: 400

trailing_comma:
  mandatory_comma: true
