//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `Podfile`.
    static let podfile = Rswift.FileResource(bundle: R.hostingBundle, name: "Podfile", pathExtension: "")
    /// Resource file `Settings.bundle`.
    static let settingsBundle = Rswift.FileResource(bundle: R.hostingBundle, name: "Settings", pathExtension: "bundle")
    /// Resource file `emoji.json`.
    static let emojiJson = Rswift.FileResource(bundle: R.hostingBundle, name: "emoji", pathExtension: "json")
    
    /// `bundle.url(forResource: "Podfile", withExtension: "")`
    static func podfile(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.podfile
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Settings", withExtension: "bundle")`
    static func settingsBundle(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.settingsBundle
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "emoji", withExtension: "json")`
    static func emojiJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.emojiJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 22 images.
  struct image {
    /// Image `ArrowDown`.
    static let arrowDown = Rswift.ImageResource(bundle: R.hostingBundle, name: "ArrowDown")
    /// Image `ArrowUp`.
    static let arrowUp = Rswift.ImageResource(bundle: R.hostingBundle, name: "ArrowUp")
    /// Image `Boost`.
    static let boost = Rswift.ImageResource(bundle: R.hostingBundle, name: "Boost")
    /// Image `Camera`.
    static let camera = Rswift.ImageResource(bundle: R.hostingBundle, name: "Camera")
    /// Image `Follow`.
    static let follow = Rswift.ImageResource(bundle: R.hostingBundle, name: "Follow")
    /// Image `HomeOutline`.
    static let homeOutline = Rswift.ImageResource(bundle: R.hostingBundle, name: "HomeOutline")
    /// Image `Home`.
    static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home")
    /// Image `MoreOutline`.
    static let moreOutline = Rswift.ImageResource(bundle: R.hostingBundle, name: "MoreOutline")
    /// Image `More`.
    static let more = Rswift.ImageResource(bundle: R.hostingBundle, name: "More")
    /// Image `NotificationOutline`.
    static let notificationOutline = Rswift.ImageResource(bundle: R.hostingBundle, name: "NotificationOutline")
    /// Image `Notification`.
    static let notification = Rswift.ImageResource(bundle: R.hostingBundle, name: "Notification")
    /// Image `NowPlaying`.
    static let nowPlaying = Rswift.ImageResource(bundle: R.hostingBundle, name: "NowPlaying")
    /// Image `PeopleOutline`.
    static let peopleOutline = Rswift.ImageResource(bundle: R.hostingBundle, name: "PeopleOutline")
    /// Image `People`.
    static let people = Rswift.ImageResource(bundle: R.hostingBundle, name: "People")
    /// Image `PhotosInline`.
    static let photosInline = Rswift.ImageResource(bundle: R.hostingBundle, name: "PhotosInline")
    /// Image `Reply`.
    static let reply = Rswift.ImageResource(bundle: R.hostingBundle, name: "Reply")
    /// Image `Star`.
    static let star = Rswift.ImageResource(bundle: R.hostingBundle, name: "Star")
    /// Image `StreamingStatus`.
    static let streamingStatus = Rswift.ImageResource(bundle: R.hostingBundle, name: "StreamingStatus")
    /// Image `visibility-direct`.
    static let visibilityDirect = Rswift.ImageResource(bundle: R.hostingBundle, name: "visibility-direct")
    /// Image `visibility-private`.
    static let visibilityPrivate = Rswift.ImageResource(bundle: R.hostingBundle, name: "visibility-private")
    /// Image `visibility-public`.
    static let visibilityPublic = Rswift.ImageResource(bundle: R.hostingBundle, name: "visibility-public")
    /// Image `visibility-unlisted`.
    static let visibilityUnlisted = Rswift.ImageResource(bundle: R.hostingBundle, name: "visibility-unlisted")
    
    /// `UIImage(named: "ArrowDown", bundle: ..., traitCollection: ...)`
    static func arrowDown(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.arrowDown, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ArrowUp", bundle: ..., traitCollection: ...)`
    static func arrowUp(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.arrowUp, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Boost", bundle: ..., traitCollection: ...)`
    static func boost(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.boost, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Camera", bundle: ..., traitCollection: ...)`
    static func camera(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camera, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Follow", bundle: ..., traitCollection: ...)`
    static func follow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.follow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "HomeOutline", bundle: ..., traitCollection: ...)`
    static func homeOutline(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.homeOutline, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "More", bundle: ..., traitCollection: ...)`
    static func more(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.more, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "MoreOutline", bundle: ..., traitCollection: ...)`
    static func moreOutline(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.moreOutline, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Notification", bundle: ..., traitCollection: ...)`
    static func notification(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.notification, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "NotificationOutline", bundle: ..., traitCollection: ...)`
    static func notificationOutline(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.notificationOutline, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "NowPlaying", bundle: ..., traitCollection: ...)`
    static func nowPlaying(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.nowPlaying, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "People", bundle: ..., traitCollection: ...)`
    static func people(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.people, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "PeopleOutline", bundle: ..., traitCollection: ...)`
    static func peopleOutline(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.peopleOutline, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "PhotosInline", bundle: ..., traitCollection: ...)`
    static func photosInline(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.photosInline, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Reply", bundle: ..., traitCollection: ...)`
    static func reply(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.reply, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Star", bundle: ..., traitCollection: ...)`
    static func star(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.star, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "StreamingStatus", bundle: ..., traitCollection: ...)`
    static func streamingStatus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.streamingStatus, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visibility-direct", bundle: ..., traitCollection: ...)`
    static func visibilityDirect(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visibilityDirect, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visibility-private", bundle: ..., traitCollection: ...)`
    static func visibilityPrivate(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visibilityPrivate, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visibility-public", bundle: ..., traitCollection: ...)`
    static func visibilityPublic(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visibilityPublic, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visibility-unlisted", bundle: ..., traitCollection: ...)`
    static func visibilityUnlisted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visibilityUnlisted, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 5 nibs.
  struct nib {
    /// Nib `MastodonPostCell`.
    static let mastodonPostCell = _R.nib._MastodonPostCell()
    /// Nib `NewPostMediaListViewController`.
    static let newPostMediaListViewController = _R.nib._NewPostMediaListViewController()
    /// Nib `TimeLineReadMoreCell`.
    static let timeLineReadMoreCell = _R.nib._TimeLineReadMoreCell()
    /// Nib `UserProfileBioTableViewCell`.
    static let userProfileBioTableViewCell = _R.nib._UserProfileBioTableViewCell()
    /// Nib `UserProfileInfoTableViewCell`.
    static let userProfileInfoTableViewCell = _R.nib._UserProfileInfoTableViewCell()
    
    /// `UINib(name: "MastodonPostCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.mastodonPostCell) instead")
    static func mastodonPostCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.mastodonPostCell)
    }
    
    /// `UINib(name: "NewPostMediaListViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.newPostMediaListViewController) instead")
    static func newPostMediaListViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.newPostMediaListViewController)
    }
    
    /// `UINib(name: "TimeLineReadMoreCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.timeLineReadMoreCell) instead")
    static func timeLineReadMoreCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.timeLineReadMoreCell)
    }
    
    /// `UINib(name: "UserProfileBioTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.userProfileBioTableViewCell) instead")
    static func userProfileBioTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.userProfileBioTableViewCell)
    }
    
    /// `UINib(name: "UserProfileInfoTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.userProfileInfoTableViewCell) instead")
    static func userProfileInfoTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.userProfileInfoTableViewCell)
    }
    
    static func mastodonPostCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MastodonPostCell? {
      return R.nib.mastodonPostCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MastodonPostCell
    }
    
    static func newPostMediaListViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.newPostMediaListViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func timeLineReadMoreCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UITableViewCell? {
      return R.nib.timeLineReadMoreCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UITableViewCell
    }
    
    static func userProfileBioTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UserProfileBioTableViewCell? {
      return R.nib.userProfileBioTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UserProfileBioTableViewCell
    }
    
    static func userProfileInfoTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UserProfileInfoTableViewCell? {
      return R.nib.userProfileInfoTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UserProfileInfoTableViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 4 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `OtherMenuAccountChangeCell`.
    static let otherMenuAccountChangeCell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "OtherMenuAccountChangeCell")
    /// Reuse identifier `list`.
    static let list: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "list")
    /// Reuse identifier `myProfile`.
    static let myProfile: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "myProfile")
    /// Reuse identifier `settings`.
    static let settings: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "settings")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 4 view controllers.
  struct segue {
    /// This struct is generated for `AddAccountIndexViewController`, and contains static references to 1 segues.
    struct addAccountIndexViewController {
      /// Segue identifier `goProgress`.
      static let goProgress: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountIndexViewController, AddAccountProgressViewController> = Rswift.StoryboardSegueIdentifier(identifier: "goProgress")
      
      /// Optionally returns a typed version of segue `goProgress`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func goProgress(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountIndexViewController, AddAccountProgressViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountIndexViewController.goProgress, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `AddAccountLoginViewController`, and contains static references to 1 segues.
    struct addAccountLoginViewController {
      /// Segue identifier `backToProgress`.
      static let backToProgress: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountLoginViewController, AddAccountProgressViewController> = Rswift.StoryboardSegueIdentifier(identifier: "backToProgress")
      
      /// Optionally returns a typed version of segue `backToProgress`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func backToProgress(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountLoginViewController, AddAccountProgressViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountLoginViewController.backToProgress, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `AddAccountProgressViewController`, and contains static references to 3 segues.
    struct addAccountProgressViewController {
      /// Segue identifier `errorBack`.
      static let errorBack: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountIndexViewController> = Rswift.StoryboardSegueIdentifier(identifier: "errorBack")
      /// Segue identifier `goSelectLoginMethod`.
      static let goSelectLoginMethod: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountSelectLoginMethodViewController> = Rswift.StoryboardSegueIdentifier(identifier: "goSelectLoginMethod")
      /// Segue identifier `goSuccess`.
      static let goSuccess: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountSuccessViewController> = Rswift.StoryboardSegueIdentifier(identifier: "goSuccess")
      
      /// Optionally returns a typed version of segue `errorBack`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func errorBack(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountIndexViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountProgressViewController.errorBack, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `goSelectLoginMethod`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func goSelectLoginMethod(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountSelectLoginMethodViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountProgressViewController.goSelectLoginMethod, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `goSuccess`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func goSuccess(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountProgressViewController, AddAccountSuccessViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountProgressViewController.goSuccess, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `AddAccountSelectLoginMethodViewController`, and contains static references to 1 segues.
    struct addAccountSelectLoginMethodViewController {
      /// Segue identifier `goMailAddressAndPasswordLogin`.
      static let goMailAddressAndPasswordLogin: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddAccountSelectLoginMethodViewController, AddAccountLoginViewController> = Rswift.StoryboardSegueIdentifier(identifier: "goMailAddressAndPasswordLogin")
      
      /// Optionally returns a typed version of segue `goMailAddressAndPasswordLogin`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func goMailAddressAndPasswordLogin(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddAccountSelectLoginMethodViewController, AddAccountLoginViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addAccountSelectLoginMethodViewController.goMailAddressAndPasswordLogin, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 6 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Login`.
    static let login = _R.storyboard.login()
    /// Storyboard `MastodonPostDetail`.
    static let mastodonPostDetail = _R.storyboard.mastodonPostDetail()
    /// Storyboard `NewPost`.
    static let newPost = _R.storyboard.newPost()
    /// Storyboard `OtherMenu`.
    static let otherMenu = _R.storyboard.otherMenu()
    /// Storyboard `ProfileCard`.
    static let profileCard = _R.storyboard.profileCard()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Login", bundle: ...)`
    static func login(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.login)
    }
    
    /// `UIStoryboard(name: "MastodonPostDetail", bundle: ...)`
    static func mastodonPostDetail(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.mastodonPostDetail)
    }
    
    /// `UIStoryboard(name: "NewPost", bundle: ...)`
    static func newPost(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.newPost)
    }
    
    /// `UIStoryboard(name: "OtherMenu", bundle: ...)`
    static func otherMenu(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.otherMenu)
    }
    
    /// `UIStoryboard(name: "ProfileCard", bundle: ...)`
    static func profileCard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.profileCard)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 5 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 31 localization keys.
    struct localizable {
      /// en translation: @% boosted your toot
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellReblogTitle = Rswift.StringResource(key: "tabs.notifications.cell.reblog.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: @% favorited your toot
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellFavouriteTitle = Rswift.StringResource(key: "tabs.notifications.cell.favourite.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: @% followed you
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellFollowTitle = Rswift.StringResource(key: "tabs.notifications.cell.follow.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: @% mentioned you
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellMentionTitle = Rswift.StringResource(key: "tabs.notifications.cell.mention.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Actions
      /// 
      /// Locales: en, ja
      static let profileActionsTitle = Rswift.StringResource(key: "profile.actions.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Block
      /// 
      /// Locales: en, ja
      static let profileActionsBlock = Rswift.StringResource(key: "profile.actions.block", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Cancel
      /// 
      /// Locales: en, ja
      static let timelineStreamingActionCancel = Rswift.StringResource(key: "timeline.streaming.action.cancel", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Cancel follow request
      /// 
      /// Locales: en, ja
      static let profileActionsFollowRequestCancel = Rswift.StringResource(key: "profile.actions.followRequestCancel", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Connect
      /// 
      /// Locales: en, ja
      static let timelineStreamingActionConnect = Rswift.StringResource(key: "timeline.streaming.action.connect", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Connected
      /// 
      /// Locales: en, ja
      static let timelineStreamingStatusConnected = Rswift.StringResource(key: "timeline.streaming.status.connected", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Disconnect
      /// 
      /// Locales: en, ja
      static let timelineStreamingActionDisconnect = Rswift.StringResource(key: "timeline.streaming.action.disconnect", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Fetch failed
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellReadmoreFetchError = Rswift.StringResource(key: "tabs.notifications.cell.readmore.fetchError", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Follow
      /// 
      /// Locales: en, ja
      static let profileActionsFollow = Rswift.StringResource(key: "profile.actions.follow", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Home
      /// 
      /// Locales: en, ja
      static let tabsHomeShortTitle = Rswift.StringResource(key: "tabs.home.shortTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Home Timeline
      /// 
      /// Locales: en, ja
      static let tabsHomeTitle = Rswift.StringResource(key: "tabs.home.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: LTL
      /// 
      /// Locales: en, ja
      static let tabsLocalTimelineShortTitle = Rswift.StringResource(key: "tabs.localTimeline.shortTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Local Timeline
      /// 
      /// Locales: en, ja
      static let tabsLocalTimelineTitle = Rswift.StringResource(key: "tabs.localTimeline.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Mute
      /// 
      /// Locales: en, ja
      static let profileActionsMute = Rswift.StringResource(key: "profile.actions.mute", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Not connected
      /// 
      /// Locales: en, ja
      static let timelineStreamingStatusNotConnected = Rswift.StringResource(key: "timeline.streaming.status.notConnected", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Nothing more
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellReadmoreDisabledTitle = Rswift.StringResource(key: "tabs.notifications.cell.readmore.disabledTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Notifications
      /// 
      /// Locales: en, ja
      static let tabsNotificationsTitle = Rswift.StringResource(key: "tabs.notifications.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Post
      /// 
      /// Locales: en, ja
      static let timelineToPostButtonTitle = Rswift.StringResource(key: "timeline.toPostButton.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Profile Card
      /// 
      /// Locales: en, ja
      static let profileActionsProfileCard = Rswift.StringResource(key: "profile.actions.profileCard", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Read more
      /// 
      /// Locales: en, ja
      static let tabsNotificationsCellReadmoreTitle = Rswift.StringResource(key: "tabs.notifications.cell.readmore.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Refresh
      /// 
      /// Locales: en, ja
      static let timelineStreamingActionRefresh = Rswift.StringResource(key: "timeline.streaming.action.refresh", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Share
      /// 
      /// Locales: en, ja
      static let profileActionsShare = Rswift.StringResource(key: "profile.actions.share", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Status: %
      /// 
      /// Locales: en, ja
      static let timelineStreamingStatusBase = Rswift.StringResource(key: "timeline.streaming.status.base", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Streaming
      /// 
      /// Locales: en, ja
      static let timelineStreamingTitle = Rswift.StringResource(key: "timeline.streaming.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Unblock
      /// 
      /// Locales: en, ja
      static let profileActionsUnblock = Rswift.StringResource(key: "profile.actions.unblock", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Unfollow
      /// 
      /// Locales: en, ja
      static let profileActionsUnfollow = Rswift.StringResource(key: "profile.actions.unfollow", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Unmute
      /// 
      /// Locales: en, ja
      static let profileActionsUnmute = Rswift.StringResource(key: "profile.actions.unmute", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      
      /// en translation: @% boosted your toot
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellReblogTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.reblog.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: @% favorited your toot
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellFavouriteTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.favourite.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: @% followed you
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellFollowTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.follow.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: @% mentioned you
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellMentionTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.mention.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Actions
      /// 
      /// Locales: en, ja
      static func profileActionsTitle(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Block
      /// 
      /// Locales: en, ja
      static func profileActionsBlock(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.block", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Cancel
      /// 
      /// Locales: en, ja
      static func timelineStreamingActionCancel(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.action.cancel", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Cancel follow request
      /// 
      /// Locales: en, ja
      static func profileActionsFollowRequestCancel(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.followRequestCancel", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Connect
      /// 
      /// Locales: en, ja
      static func timelineStreamingActionConnect(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.action.connect", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Connected
      /// 
      /// Locales: en, ja
      static func timelineStreamingStatusConnected(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.status.connected", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Disconnect
      /// 
      /// Locales: en, ja
      static func timelineStreamingActionDisconnect(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.action.disconnect", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Fetch failed
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellReadmoreFetchError(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.readmore.fetchError", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Follow
      /// 
      /// Locales: en, ja
      static func profileActionsFollow(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.follow", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Home
      /// 
      /// Locales: en, ja
      static func tabsHomeShortTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.home.shortTitle", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Home Timeline
      /// 
      /// Locales: en, ja
      static func tabsHomeTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.home.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: LTL
      /// 
      /// Locales: en, ja
      static func tabsLocalTimelineShortTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.localTimeline.shortTitle", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Local Timeline
      /// 
      /// Locales: en, ja
      static func tabsLocalTimelineTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.localTimeline.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Mute
      /// 
      /// Locales: en, ja
      static func profileActionsMute(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.mute", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Not connected
      /// 
      /// Locales: en, ja
      static func timelineStreamingStatusNotConnected(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.status.notConnected", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Nothing more
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellReadmoreDisabledTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.readmore.disabledTitle", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Notifications
      /// 
      /// Locales: en, ja
      static func tabsNotificationsTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Post
      /// 
      /// Locales: en, ja
      static func timelineToPostButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("timeline.toPostButton.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Profile Card
      /// 
      /// Locales: en, ja
      static func profileActionsProfileCard(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.profileCard", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Read more
      /// 
      /// Locales: en, ja
      static func tabsNotificationsCellReadmoreTitle(_: Void = ()) -> String {
        return NSLocalizedString("tabs.notifications.cell.readmore.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Refresh
      /// 
      /// Locales: en, ja
      static func timelineStreamingActionRefresh(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.action.refresh", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Share
      /// 
      /// Locales: en, ja
      static func profileActionsShare(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.share", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Status: %
      /// 
      /// Locales: en, ja
      static func timelineStreamingStatusBase(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.status.base", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Streaming
      /// 
      /// Locales: en, ja
      static func timelineStreamingTitle(_: Void = ()) -> String {
        return NSLocalizedString("timeline.streaming.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Unblock
      /// 
      /// Locales: en, ja
      static func profileActionsUnblock(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.unblock", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Unfollow
      /// 
      /// Locales: en, ja
      static func profileActionsUnfollow(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.unfollow", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Unmute
      /// 
      /// Locales: en, ja
      static func profileActionsUnmute(_: Void = ()) -> String {
        return NSLocalizedString("profile.actions.unmute", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.login` struct is generated, and contains static references to 31 localization keys.
    struct login {
      /// en translation: 1 / 4
      /// 
      /// Locales: en, ja
      static let vrU34PZrText = Rswift.StringResource(key: "vrU-34-PZr.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: By logging in, you agree to {tos} and {privacyPolicy} of this instance.
      /// 
      /// Locales: en, ja
      static let loginMethodAcceptTermsTitle = Rswift.StringResource(key: "loginMethod.acceptTerms.title", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Checking server...
      /// 
      /// Locales: en, ja
      static let yQUZVZCdText = Rswift.StringResource(key: "yQU-ZV-ZCd.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Enter instance hostname
      /// 
      /// Locales: en, ja
      static let ryeghc8iText = Rswift.StringResource(key: "RYE-gH-C8i.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Fetching Account Information...
      /// 
      /// Locales: en, ja
      static let authStage4 = Rswift.StringResource(key: "authStage.4", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Fetching Server Information...
      /// 
      /// Locales: en, ja
      static let authStage1 = Rswift.StringResource(key: "authStage.1", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Go to timeline
      /// 
      /// Locales: en, ja
      static let vhHLD1z5NormalTitle = Rswift.StringResource(key: "vhH-lD-1z5.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: How to select login method
      /// 
      /// Locales: en, ja
      static let loginMethodHelpTitle = Rswift.StringResource(key: "loginMethod.help.title", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: How to select method?
      /// 
      /// Locales: en, ja
      static let qZv1VZeeNormalTitle = Rswift.StringResource(key: "qZv-1V-Zee.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Logging in...
      /// 
      /// Locales: en, ja
      static let e3hSrGGoText = Rswift.StringResource(key: "e3h-sr-GGo.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static let hxxWi3lmTitle = Rswift.StringResource(key: "hxx-wi-3lm.title", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static let mwcl4DqaTitle = Rswift.StringResource(key: "MWC-l4-dqa.title", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static let tkdKiKUCNormalTitle = Rswift.StringResource(key: "Tkd-Ki-kUC.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static let yPErJ0gNormalTitle = Rswift.StringResource(key: "9yP-er-J0g.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static let yPErJ0gSelectedTitle = Rswift.StringResource(key: "9yP-er-J0g.selectedTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login with Safari (Recommended)
      /// 
      /// Locales: en, ja
      static let rjAAJcvNormalTitle = Rswift.StringResource(key: "4Rj-aA-jcv.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login with credentials
      /// 
      /// Locales: en, ja
      static let gjd7xUGvText = Rswift.StringResource(key: "gjd-7x-UGv.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Login with credentials
      /// 
      /// Locales: en, ja
      static let uNRDQTp7NormalTitle = Rswift.StringResource(key: "uNR-dQ-Tp7.normalTitle", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Normally, please select "Login with Safari". If "Login with Safari" is not working, please select "Login with credentials". "Login with credentials" may not working on some instances and accounts.
      /// 
      /// Locales: en, ja
      static let loginMethodHelpMessage = Rswift.StringResource(key: "loginMethod.help.message", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Password
      /// 
      /// Locales: en, ja
      static let icDSJGQRPlaceholder = Rswift.StringResource(key: "IcD-SJ-gQR.placeholder", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Please Login
      /// 
      /// Locales: en, ja
      static let authStage3 = Rswift.StringResource(key: "authStage.3", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Registering App Information...
      /// 
      /// Locales: en, ja
      static let authStage2 = Rswift.StringResource(key: "authStage.2", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Select login method
      /// 
      /// Locales: en, ja
      static let veUJAMdKText = Rswift.StringResource(key: "veU-jA-mdK.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Welcome,  @%
      /// 
      /// Locales: en, ja
      static let fNLLLNGUText = Rswift.StringResource(key: "fNL-LL-nGU.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: email address
      /// 
      /// Locales: en, ja
      static let hEsGPM5fPlaceholder = Rswift.StringResource(key: "hEs-gP-M5f.placeholder", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: iMast
      /// 
      /// Locales: en, ja
      static let wqHKGMcdText = Rswift.StringResource(key: "wqH-KG-Mcd.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: mstdn.jp
      /// 
      /// Locales: en, ja
      static let hrIJcFxPPlaceholder = Rswift.StringResource(key: "HrI-Jc-fxP.placeholder", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: privacy policy
      /// 
      /// Locales: en, ja
      static let loginMethodAcceptTermsPrivacyPolicy = Rswift.StringResource(key: "loginMethod.acceptTerms.privacyPolicy", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: terms of service
      /// 
      /// Locales: en, ja
      static let loginMethodAcceptTermsTerms = Rswift.StringResource(key: "loginMethod.acceptTerms.terms", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: ログイン
      /// 
      /// Locales: en, ja
      static let eRuFCCfATitle = Rswift.StringResource(key: "eRu-fC-cfA.title", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: ログインすると、利用規約及びプライバシーポリシーに同意したことになります。
      /// 
      /// Locales: en, ja
      static let fvR0FAIoText = Rswift.StringResource(key: "FvR-0F-AIo.text", tableName: "Login", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      
      /// en translation: 1 / 4
      /// 
      /// Locales: en, ja
      static func vrU34PZrText(_: Void = ()) -> String {
        return NSLocalizedString("vrU-34-PZr.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: By logging in, you agree to {tos} and {privacyPolicy} of this instance.
      /// 
      /// Locales: en, ja
      static func loginMethodAcceptTermsTitle(_: Void = ()) -> String {
        return NSLocalizedString("loginMethod.acceptTerms.title", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Checking server...
      /// 
      /// Locales: en, ja
      static func yQUZVZCdText(_: Void = ()) -> String {
        return NSLocalizedString("yQU-ZV-ZCd.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Enter instance hostname
      /// 
      /// Locales: en, ja
      static func ryeghc8iText(_: Void = ()) -> String {
        return NSLocalizedString("RYE-gH-C8i.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Fetching Account Information...
      /// 
      /// Locales: en, ja
      static func authStage4(_: Void = ()) -> String {
        return NSLocalizedString("authStage.4", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Fetching Server Information...
      /// 
      /// Locales: en, ja
      static func authStage1(_: Void = ()) -> String {
        return NSLocalizedString("authStage.1", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Go to timeline
      /// 
      /// Locales: en, ja
      static func vhHLD1z5NormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("vhH-lD-1z5.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: How to select login method
      /// 
      /// Locales: en, ja
      static func loginMethodHelpTitle(_: Void = ()) -> String {
        return NSLocalizedString("loginMethod.help.title", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: How to select method?
      /// 
      /// Locales: en, ja
      static func qZv1VZeeNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("qZv-1V-Zee.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Logging in...
      /// 
      /// Locales: en, ja
      static func e3hSrGGoText(_: Void = ()) -> String {
        return NSLocalizedString("e3h-sr-GGo.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static func hxxWi3lmTitle(_: Void = ()) -> String {
        return NSLocalizedString("hxx-wi-3lm.title", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static func mwcl4DqaTitle(_: Void = ()) -> String {
        return NSLocalizedString("MWC-l4-dqa.title", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static func tkdKiKUCNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("Tkd-Ki-kUC.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static func yPErJ0gNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("9yP-er-J0g.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login
      /// 
      /// Locales: en, ja
      static func yPErJ0gSelectedTitle(_: Void = ()) -> String {
        return NSLocalizedString("9yP-er-J0g.selectedTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login with Safari (Recommended)
      /// 
      /// Locales: en, ja
      static func rjAAJcvNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("4Rj-aA-jcv.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login with credentials
      /// 
      /// Locales: en, ja
      static func gjd7xUGvText(_: Void = ()) -> String {
        return NSLocalizedString("gjd-7x-UGv.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Login with credentials
      /// 
      /// Locales: en, ja
      static func uNRDQTp7NormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("uNR-dQ-Tp7.normalTitle", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Normally, please select "Login with Safari". If "Login with Safari" is not working, please select "Login with credentials". "Login with credentials" may not working on some instances and accounts.
      /// 
      /// Locales: en, ja
      static func loginMethodHelpMessage(_: Void = ()) -> String {
        return NSLocalizedString("loginMethod.help.message", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Password
      /// 
      /// Locales: en, ja
      static func icDSJGQRPlaceholder(_: Void = ()) -> String {
        return NSLocalizedString("IcD-SJ-gQR.placeholder", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Please Login
      /// 
      /// Locales: en, ja
      static func authStage3(_: Void = ()) -> String {
        return NSLocalizedString("authStage.3", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Registering App Information...
      /// 
      /// Locales: en, ja
      static func authStage2(_: Void = ()) -> String {
        return NSLocalizedString("authStage.2", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Select login method
      /// 
      /// Locales: en, ja
      static func veUJAMdKText(_: Void = ()) -> String {
        return NSLocalizedString("veU-jA-mdK.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Welcome,  @%
      /// 
      /// Locales: en, ja
      static func fNLLLNGUText(_: Void = ()) -> String {
        return NSLocalizedString("fNL-LL-nGU.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: email address
      /// 
      /// Locales: en, ja
      static func hEsGPM5fPlaceholder(_: Void = ()) -> String {
        return NSLocalizedString("hEs-gP-M5f.placeholder", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: iMast
      /// 
      /// Locales: en, ja
      static func wqHKGMcdText(_: Void = ()) -> String {
        return NSLocalizedString("wqH-KG-Mcd.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: mstdn.jp
      /// 
      /// Locales: en, ja
      static func hrIJcFxPPlaceholder(_: Void = ()) -> String {
        return NSLocalizedString("HrI-Jc-fxP.placeholder", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: privacy policy
      /// 
      /// Locales: en, ja
      static func loginMethodAcceptTermsPrivacyPolicy(_: Void = ()) -> String {
        return NSLocalizedString("loginMethod.acceptTerms.privacyPolicy", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: terms of service
      /// 
      /// Locales: en, ja
      static func loginMethodAcceptTermsTerms(_: Void = ()) -> String {
        return NSLocalizedString("loginMethod.acceptTerms.terms", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: ログイン
      /// 
      /// Locales: en, ja
      static func eRuFCCfATitle(_: Void = ()) -> String {
        return NSLocalizedString("eRu-fC-cfA.title", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: ログインすると、利用規約及びプライバシーポリシーに同意したことになります。
      /// 
      /// Locales: en, ja
      static func fvR0FAIoText(_: Void = ()) -> String {
        return NSLocalizedString("FvR-0F-AIo.text", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.newPost` struct is generated, and contains static references to 7 localization keys.
    struct newPost {
      /// en translation:  0
      /// 
      /// Locales: en, ja
      static let zg4V9GJNormalTitle = Rswift.StringResource(key: "9zg-4V-9GJ.normalTitle", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: CW
      /// 
      /// Locales: en, ja
      static let paxYe0d9Title = Rswift.StringResource(key: "pax-Ye-0d9.title", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: CW Warning text
      /// 
      /// Locales: en, ja
      static let ncKaJwdPlaceholder = Rswift.StringResource(key: "8NC-Ka-Jwd.placeholder", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Compose Post
      /// 
      /// Locales: en, ja
      static let lfAApGmeTitle = Rswift.StringResource(key: "LfA-Ap-gme.title", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: NSFW
      /// 
      /// Locales: en, ja
      static let pddnqDhaTitle = Rswift.StringResource(key: "PDD-NQ-dha.title", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Send
      /// 
      /// Locales: en, ja
      static let vdu9C5JKTitle = Rswift.StringResource(key: "vdu-9C-5JK.title", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: rin@mastodon.example.com Reply to: @uzuki: 凛ちゃんとデートです♪
      /// 
      /// Locales: en, ja
      static let jxIaK2aText = Rswift.StringResource(key: "3JX-ia-k2a.text", tableName: "NewPost", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      
      /// en translation:  0
      /// 
      /// Locales: en, ja
      static func zg4V9GJNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("9zg-4V-9GJ.normalTitle", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: CW
      /// 
      /// Locales: en, ja
      static func paxYe0d9Title(_: Void = ()) -> String {
        return NSLocalizedString("pax-Ye-0d9.title", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: CW Warning text
      /// 
      /// Locales: en, ja
      static func ncKaJwdPlaceholder(_: Void = ()) -> String {
        return NSLocalizedString("8NC-Ka-Jwd.placeholder", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Compose Post
      /// 
      /// Locales: en, ja
      static func lfAApGmeTitle(_: Void = ()) -> String {
        return NSLocalizedString("LfA-Ap-gme.title", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: NSFW
      /// 
      /// Locales: en, ja
      static func pddnqDhaTitle(_: Void = ()) -> String {
        return NSLocalizedString("PDD-NQ-dha.title", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Send
      /// 
      /// Locales: en, ja
      static func vdu9C5JKTitle(_: Void = ()) -> String {
        return NSLocalizedString("vdu-9C-5JK.title", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: rin@mastodon.example.com Reply to: @uzuki: 凛ちゃんとデートです♪
      /// 
      /// Locales: en, ja
      static func jxIaK2aText(_: Void = ()) -> String {
        return NSLocalizedString("3JX-ia-k2a.text", tableName: "NewPost", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.otherMenu` struct is generated, and contains static references to 16 localization keys.
    struct otherMenu {
      /// en translation: Add
      /// 
      /// Locales: en, ja
      static let rltBv3z1Title = Rswift.StringResource(key: "RLT-bv-3z1.title", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Current: @%
      /// 
      /// Locales: en, ja
      static let u6oPDFAoText = Rswift.StringResource(key: "u6o-PD-FAo.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Feedback
      /// 
      /// Locales: en, ja
      static let khmBGWukText = Rswift.StringResource(key: "khm-bG-wuk.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: GitHub Issues
      /// 
      /// Locales: en, ja
      static let hz61ILDFText = Rswift.StringResource(key: "hz6-1I-lDF.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Help
      /// 
      /// Locales: en, ja
      static let uRKWEXFbText = Rswift.StringResource(key: "uRK-WE-xFb.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Help / Feedback
      /// 
      /// Locales: en, ja
      static let btXv8G4Text = Rswift.StringResource(key: "2bt-xv-8G4.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Help / Feedback
      /// 
      /// Locales: en, ja
      static let uStBSK30Title = Rswift.StringResource(key: "uSt-bS-k30.title", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Lists
      /// 
      /// Locales: en, ja
      static let tloCgUrgText = Rswift.StringResource(key: "tlo-Cg-Urg.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: My Profile
      /// 
      /// Locales: en, ja
      static let fOoWeUfbText = Rswift.StringResource(key: "fOo-We-ufb.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Others
      /// 
      /// Locales: en, ja
      static let nR3CvGJDTitle = Rswift.StringResource(key: "nR3-cv-gJD.title", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Others
      /// 
      /// Locales: en, ja
      static let ycOQPHO8Title = Rswift.StringResource(key: "ycO-qP-HO8.title", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Settings
      /// 
      /// Locales: en, ja
      static let yHs8Q6OSText = Rswift.StringResource(key: "YHs-8Q-6OS.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Subtitle
      /// 
      /// Locales: en, ja
      static let zXuCiHLKText = Rswift.StringResource(key: "ZXu-Ci-hLK.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Switch active account
      /// 
      /// Locales: en, ja
      static let dGXRGJsText = Rswift.StringResource(key: "5dG-XR-GJs.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Switch active account
      /// 
      /// Locales: en, ja
      static let uAMHWNgRTitle = Rswift.StringResource(key: "uAM-HW-NgR.title", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Title
      /// 
      /// Locales: en, ja
      static let eFLVHUdSText = Rswift.StringResource(key: "eFL-VH-udS.text", tableName: "OtherMenu", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      
      /// en translation: Add
      /// 
      /// Locales: en, ja
      static func rltBv3z1Title(_: Void = ()) -> String {
        return NSLocalizedString("RLT-bv-3z1.title", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Current: @%
      /// 
      /// Locales: en, ja
      static func u6oPDFAoText(_: Void = ()) -> String {
        return NSLocalizedString("u6o-PD-FAo.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Feedback
      /// 
      /// Locales: en, ja
      static func khmBGWukText(_: Void = ()) -> String {
        return NSLocalizedString("khm-bG-wuk.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: GitHub Issues
      /// 
      /// Locales: en, ja
      static func hz61ILDFText(_: Void = ()) -> String {
        return NSLocalizedString("hz6-1I-lDF.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Help
      /// 
      /// Locales: en, ja
      static func uRKWEXFbText(_: Void = ()) -> String {
        return NSLocalizedString("uRK-WE-xFb.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Help / Feedback
      /// 
      /// Locales: en, ja
      static func btXv8G4Text(_: Void = ()) -> String {
        return NSLocalizedString("2bt-xv-8G4.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Help / Feedback
      /// 
      /// Locales: en, ja
      static func uStBSK30Title(_: Void = ()) -> String {
        return NSLocalizedString("uSt-bS-k30.title", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Lists
      /// 
      /// Locales: en, ja
      static func tloCgUrgText(_: Void = ()) -> String {
        return NSLocalizedString("tlo-Cg-Urg.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: My Profile
      /// 
      /// Locales: en, ja
      static func fOoWeUfbText(_: Void = ()) -> String {
        return NSLocalizedString("fOo-We-ufb.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Others
      /// 
      /// Locales: en, ja
      static func nR3CvGJDTitle(_: Void = ()) -> String {
        return NSLocalizedString("nR3-cv-gJD.title", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Others
      /// 
      /// Locales: en, ja
      static func ycOQPHO8Title(_: Void = ()) -> String {
        return NSLocalizedString("ycO-qP-HO8.title", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Settings
      /// 
      /// Locales: en, ja
      static func yHs8Q6OSText(_: Void = ()) -> String {
        return NSLocalizedString("YHs-8Q-6OS.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Subtitle
      /// 
      /// Locales: en, ja
      static func zXuCiHLKText(_: Void = ()) -> String {
        return NSLocalizedString("ZXu-Ci-hLK.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Switch active account
      /// 
      /// Locales: en, ja
      static func dGXRGJsText(_: Void = ()) -> String {
        return NSLocalizedString("5dG-XR-GJs.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Switch active account
      /// 
      /// Locales: en, ja
      static func uAMHWNgRTitle(_: Void = ()) -> String {
        return NSLocalizedString("uAM-HW-NgR.title", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Title
      /// 
      /// Locales: en, ja
      static func eFLVHUdSText(_: Void = ()) -> String {
        return NSLocalizedString("eFL-VH-udS.text", tableName: "OtherMenu", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.search` struct is generated, and contains static references to 5 localization keys.
    struct search {
      /// ja translation: アカウント
      /// 
      /// Locales: ja, en
      static let sectionsAccountsTitle = Rswift.StringResource(key: "sections.accounts.title", tableName: "Search", bundle: R.hostingBundle, locales: ["ja", "en"], comment: nil)
      /// ja translation: トレンドタグ (更新: %@)
      /// 
      /// Locales: ja, en
      static let sectionsTrendTagsTitle = Rswift.StringResource(key: "sections.trendTags.title", tableName: "Search", bundle: R.hostingBundle, locales: ["ja", "en"], comment: nil)
      /// ja translation: ハッシュタグ
      /// 
      /// Locales: ja, en
      static let sectionsHashtagsTitle = Rswift.StringResource(key: "sections.hashtags.title", tableName: "Search", bundle: R.hostingBundle, locales: ["ja", "en"], comment: nil)
      /// ja translation: 投稿
      /// 
      /// Locales: ja, en
      static let sectionsPostsTitle = Rswift.StringResource(key: "sections.posts.title", tableName: "Search", bundle: R.hostingBundle, locales: ["ja", "en"], comment: nil)
      /// ja translation: 検索
      /// 
      /// Locales: ja, en
      static let title = Rswift.StringResource(key: "title", tableName: "Search", bundle: R.hostingBundle, locales: ["ja", "en"], comment: nil)
      
      /// ja translation: アカウント
      /// 
      /// Locales: ja, en
      static func sectionsAccountsTitle(_: Void = ()) -> String {
        return NSLocalizedString("sections.accounts.title", tableName: "Search", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: トレンドタグ (更新: %@)
      /// 
      /// Locales: ja, en
      static func sectionsTrendTagsTitle(_ value1: String) -> String {
        return String(format: NSLocalizedString("sections.trendTags.title", tableName: "Search", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// ja translation: ハッシュタグ
      /// 
      /// Locales: ja, en
      static func sectionsHashtagsTitle(_: Void = ()) -> String {
        return NSLocalizedString("sections.hashtags.title", tableName: "Search", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 投稿
      /// 
      /// Locales: ja, en
      static func sectionsPostsTitle(_: Void = ()) -> String {
        return NSLocalizedString("sections.posts.title", tableName: "Search", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 検索
      /// 
      /// Locales: ja, en
      static func title(_: Void = ()) -> String {
        return NSLocalizedString("title", tableName: "Search", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _MastodonPostCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "MastodonPostCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MastodonPostCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MastodonPostCell
      }
      
      func secondView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[1] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _NewPostMediaListViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "NewPostMediaListViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _TimeLineReadMoreCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TimeLineReadMoreCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UITableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UITableViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _UserProfileBioTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "UserProfileBioTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UserProfileBioTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UserProfileBioTableViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _UserProfileInfoTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "UserProfileInfoTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UserProfileInfoTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UserProfileInfoTableViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try login.validate()
      try profileCard.validate()
      try mastodonPostDetail.validate()
      try otherMenu.validate()
      try launchScreen.validate()
      try newPost.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct login: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AddAccountIndexViewController
      
      let bundle = R.hostingBundle
      let logintop = StoryboardViewControllerResource<AddAccountIndexViewController>(identifier: "logintop")
      let name = "Login"
      let progress = StoryboardViewControllerResource<AddAccountProgressViewController>(identifier: "progress")
      
      func logintop(_: Void = ()) -> AddAccountIndexViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: logintop)
      }
      
      func progress(_: Void = ()) -> AddAccountProgressViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: progress)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.login().logintop() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'logintop' could not be loaded from storyboard 'Login' as 'AddAccountIndexViewController'.") }
        if _R.storyboard.login().progress() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'progress' could not be loaded from storyboard 'Login' as 'AddAccountProgressViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct mastodonPostDetail: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = MastodonPostDetailTableViewController
      
      let bundle = R.hostingBundle
      let name = "MastodonPostDetail"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct newPost: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NewPostViewController
      
      let bundle = R.hostingBundle
      let name = "NewPost"
      
      static func validate() throws {
        if UIKit.UIImage(named: "Camera") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Camera' is used in storyboard 'NewPost', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visibility-public") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visibility-public' is used in storyboard 'NewPost', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ArrowUp") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ArrowUp' is used in storyboard 'NewPost', but couldn't be loaded.") }
        if UIKit.UIImage(named: "NowPlaying") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'NowPlaying' is used in storyboard 'NewPost', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct otherMenu: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "OtherMenu"
      
      static func validate() throws {
        if UIKit.UIImage(named: "More") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'More' is used in storyboard 'OtherMenu', but couldn't be loaded.") }
        if UIKit.UIImage(named: "MoreOutline") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'MoreOutline' is used in storyboard 'OtherMenu', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct profileCard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ProfileCardViewController
      
      let bundle = R.hostingBundle
      let name = "ProfileCard"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
