# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require "xcodeproj"

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "iMast.xcodeproj")

    version = get_version_number(xcodeproj: "iMast.xcodeproj", target: "iMast") + "b" + get_build_number(xcodeproj: "iMast.xcodeproj")
    git_commit(path: ["./*/Info.plist", "./iMast.xcodeproj/project.pbxproj"], message: ":rocket: " + version)
    add_git_tag(tag: version)
    push_to_git_remote

    build_app(workspace: "iMast.xcworkspace", scheme: "iMast")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :nightly do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "iMast.xcodeproj")

    old_tag = last_git_tag
    logs = sh("git", "log", '--pretty=format:- %s (%h)', old_tag + "...master").split("\n").select { |line| !line.start_with? "- Merge branch 'master'" }.join("\n")

    version = get_version_number(xcodeproj: "iMast.xcodeproj", target: "iMast") + "b" + get_build_number(xcodeproj: "iMast.xcodeproj")

    changelog = "※タイムライン再実装中に伴い絶賛デグレ中 間違えてアップグレードしちゃったらTestFlight内のiMastのページから「前のビルド」で3.2→3.2 (126)をインストールするとデグレ前に戻ります\n進捗→ https://github.com/cinderella-project/iMast/issues/136 \nThis is nightly build.\n\ncommits:\n" + logs + "\n\nGitHub: https://github.com/cinderella-project/iMast/compare/" + old_tag + "..." + version
    changelog = changelog.gsub("→", "->")

    git_commit(path: ["./*/Info.plist", "./iMast.xcodeproj/project.pbxproj"], message: ":rocket: " + version)
    push_to_git_remote
    add_git_tag(tag: version, message: changelog)

    get_provisioning_profile

    project = Xcodeproj::Project.open("../iMast.xcodeproj")
    bundle_id = "jp.pronama.imast"
    
    target = project.targets.find { |target| target.build_settings("Release")["PRODUCT_BUNDLE_IDENTIFIER"] == bundle_id}
    appexs = target.dependencies.select { |dep| dep.target.product_type == "com.apple.product-type.app-extension" }
    
    for appex in appexs do
       get_provisioning_profile(app_identifier: appex.target.build_settings("Release")["PRODUCT_BUNDLE_IDENTIFIER"])
    end

    build_app(workspace: "iMast.xcworkspace", scheme: "iMast")
    upload_to_testflight(changelog: changelog, distribute_external: true, wait_processing_interval: 90, groups: ["外部テスター"])
    push_to_git_remote
  end
end
