name: Prepare
description: Prepare
inputs:
  target-os:
    description: macOS, iOS, etc...
    required: true
runs:
  using: composite
  steps:
    - name: bundle install
      run: bundle update --bundler && bundle config set frozen true && bundle install
      shell: bash
    - name: Install CocoaPods dependencies
      run: bundle exec pod install
      shell: bash
    - run: git config --global core.quotepath false # for Ikemen on SwiftPM
      shell: bash
    - name: Download SwiftPM dependencies
      run: xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile -workspace ./iMast.xcworkspace -scheme "iMast iOS"
      shell: bash
    - name: Download Platform
      run: |
        for i in $(seq 1 3); do
          xcodebuild -downloadPlatform ${{ inputs.target-os }} && break
        done
      if: inputs.target-os != 'macOS'
      shell: bash
    - name: Ensure there are no diff
      run: git add -A && git diff --exit-code HEAD
      shell: bash