name: Prepare
description: Prepare
inputs:
  target-os:
    description: iOS, etc...
    required: true
runs:
  using: composite
  steps:
    - name: Disable Spotlight
      run: sudo mdutil -a -i off
      shell: bash
    - name: Install CocoaPods
      run: brew install cocoapods
      shell: bash
    - name: Install CocoaPods dependencies
      run: pod install
      shell: bash
    - run: git config --global core.quotepath false # for Ikemen on SwiftPM
      shell: bash
    - name: Check prebuilt swift-syntax is available (or not)
      shell: bash
      run: |
        SWIFT_SYNTAX_VERSION=$(jq -r '.pins[] | select(.identity == "swift-syntax").state.version' ./Sources/Package/Package.resolved)
        SWIFT_COMPILER_VERSION=$(xcrun swiftc -print-target-info | jq -r .swiftCompilerTag)
        SDK_VERSION=$(plutil -extract CanonicalName raw -o - "$(xcrun --sdk macosx --show-sdk-path)/SDKSettings.plist")
        curl -Lv --fail-with-body "https://download.swift.org/prebuilts/swift-syntax/$SWIFT_SYNTAX_VERSION/$SWIFT_COMPILER_VERSION-$SDK_VERSION.json"
    - name: Download SwiftPM dependencies
      run: xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile -workspace ./iMast.xcworkspace -scheme "iMast iOS"
      shell: bash
    - name: Download Platform
      run: |
        for i in $(seq 1 3); do
          xcodebuild -downloadPlatform ${{ inputs.target-os }} && break
        done
      shell: bash
    - name: Ensure there are no diff
      run: git add -A && git diff --exit-code HEAD
      shell: bash