name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  _main_xcode: &main_xcode "26.4"
  _main_machine: &main_machine "macOS-26"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode: [*main_xcode]
        os:
          - macOS
          - iOS
          - visionOS
        machine: [*main_machine]
    runs-on: ${{ matrix.machine }}
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - uses: ./.github/actions/prepare
      with:
        target-os: ${{ matrix.os }}
    - name: Build (iOS/visionOS)
      if: matrix.os != 'macOS'
      run: set -o pipefail && xcodebuild clean build -workspace iMast.xcworkspace -scheme "iMast iOS" -destination "generic/platform=${{ matrix.os }}" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
    - name: Build (macOS)
      if: matrix.os == 'macOS'
      run: set -o pipefail && xcodebuild clean build -workspace iMast.xcworkspace -scheme "iMast Mac (App Store)" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  build_for_test:
    strategy:
      fail-fast: true
      matrix:
        os: [iOS]
    runs-on: *main_machine
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env._main_xcode }}.app
    - uses: ./.github/actions/prepare
      with:
        target-os: ${{ matrix.os }}
    - name: Build for Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing \
          -workspace iMast.xcworkspace \
          -scheme "iMast iOS" \
          -destination "generic/platform=${{ matrix.os }} Simulator" \
          -testProductsPath ./iMast_iOS.xctestproducts \
        | xcpretty -c
    - run: tar czf iMast_iOS.xctestproducts.tar.gz iMast_iOS.xctestproducts
    - uses: actions/upload-artifact@v7
      with:
        name: iMast_iOS.${{ matrix.os }}.xctestproducts.tar.gz
        path: iMast_iOS.xctestproducts.tar.gz
        compression-level: 0
  test:
    needs: build_for_test
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        os:
          - iOS
        device_key: [
          # preferred
          "iPhone_4_7", # smallest screen
          "iPad_9_7", # not latest os
          "iPhone_5_5", # not latest os
          # others
          "iPhone_6_9",
          "iPhone_6_5",
          "iPhone_6_3",
          "iPhone_6_1",
          "iPhone_4_7",
          "iPad_13_0",
          "iPad_11_0",
          "iPad_12_9",
          "iPad_10_5",
        ]
    runs-on: *main_machine
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env._main_xcode }}.app
    - name: Download Build Artifacts
      uses: actions/download-artifact@v7
      with:
        name: iMast_iOS.${{ matrix.os }}.xctestproducts.tar.gz
    - run: tar xzf iMast_iOS.xctestproducts.tar.gz && rm iMast_iOS.xctestproducts.tar.gz
    - name: Test (iOS)
      run: |
        echo "::group::Setup mock server"
        pushd mock_server
        corepack enable
        pnpm install --frozen-lockfile
        popd
        echo "::endgroup::"
        python3 .github/test_on_multiple_devices.py ${{ matrix.device_key }}
    - name: Archive Test Results
      if: always()
      run: tar cf test_results.tar test_results
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-results_${{ matrix.os }}_Xcode.${{ env._main_xcode }}.tar
        path: test_results.tar