name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      test_all_devices:
        description: "Test on all devices (for taking screenshots)"
        required: false
        default: false
        type: boolean

env:
  _main_xcode: &main_xcode "26.4"
  _main_machine: &main_machine "macOS-26"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode: [*main_xcode]
        os:
          - macOS
          - iOS
          - visionOS
        machine: [*main_machine]
    runs-on: ${{ matrix.machine }}
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - uses: ./.github/actions/prepare
      with:
        target-os: ${{ matrix.os }}
    - name: Build (iOS/visionOS)
      if: matrix.os != 'macOS'
      run: set -o pipefail && xcodebuild clean build -workspace iMast.xcworkspace -scheme "iMast iOS" -destination "generic/platform=${{ matrix.os }}" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
    - name: Build (macOS)
      if: matrix.os == 'macOS'
      run: set -o pipefail && xcodebuild clean build -workspace iMast.xcworkspace -scheme "iMast Mac (App Store)" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c
  build_for_test:
    strategy:
      fail-fast: true
      matrix:
        os: [iOS]
    runs-on: *main_machine
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env._main_xcode }}.app
    - uses: ./.github/actions/prepare
      with:
        target-os: ${{ matrix.os }}
    - name: Build for Test
      run: |
        set -o pipefail
        xcodebuild build-for-testing \
          -workspace iMast.xcworkspace \
          -scheme "iMast iOS" \
          -destination "generic/platform=${{ matrix.os }} Simulator" \
          -testProductsPath ./iMast_iOS.xctestproducts \
        | xcpretty -c
    - run: tar czf iMast_iOS.xctestproducts.tar.gz iMast_iOS.xctestproducts
    - uses: actions/upload-artifact@v7
      with:
        name: iMast_iOS.${{ matrix.os }}.xctestproducts.tar.gz
        path: iMast_iOS.xctestproducts.tar.gz
        compression-level: 0
  calc_test_device_keys:
    runs-on: ubuntu-slim
    outputs:
      result: ${{ steps.calc.outputs.result }}
    steps:
    - uses: actions/github-script@v9
      id: calc
      env:
        TEST_ALL_DEVICES: ${{ inputs.test_all_devices }}
      with:
        script: |
          const preferredKeys = [
            "iPhone_4_7",  // smallest screen
            "iPad_13_0",   // modern iPad
            "iPad_9_7",    // iOS 17
            "iPhone_5_5",  // iOS 16
          ]
          const allKeys = [
            ...preferredKeys,
            "iPhone_6_9",
            "iPhone_6_5",
            "iPhone_6_3",
            "iPhone_6_1",
            "iPad_11_0",
            "iPad_12_9",
            "iPad_10_5",
          ]
          if (process.env.TEST_ALL_DEVICES === "true") {
            return allKeys
          } else {
            return preferredKeys
          }
  test:
    needs:
    - build_for_test
    - calc_test_device_keys
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os:
          - iOS
        device_key: ${{ fromJson(needs.calc_test_device_keys.outputs.result) }}
    runs-on: *main_machine
    concurrency:
      group: "${{ github.workflow }}_test_${{ github.ref }}_${{ matrix.device_key }}"
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env._main_xcode }}.app
    - name: Download Build Artifacts
      uses: actions/download-artifact@v7
      with:
        name: iMast_iOS.${{ matrix.os }}.xctestproducts.tar.gz
    - run: tar xzf iMast_iOS.xctestproducts.tar.gz && rm iMast_iOS.xctestproducts.tar.gz
    - name: Download Runtime
      run: python3 .github/test_on_multiple_devices.py ${{ matrix.device_key }}
      env:
        DOWNLOAD_ONLY: "yes"
    - name: Test (iOS)
      run: |
        echo "::group::Setup mock server"
        pushd mock_server
        corepack enable
        pnpm install --frozen-lockfile
        popd
        echo "::endgroup::"
        python3 .github/test_on_multiple_devices.py ${{ matrix.device_key }}
    - name: Archive Test Results
      if: always()
      run: tar cf test_results.tar test_results
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-results_${{ matrix.os }}_${{ matrix.device_key }}_Xcode.${{ env._main_xcode }}.tar
        path: test_results.tar
  extract_screenshots:
    needs: test
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v1
    - name: Download Test Results
      uses: actions/download-artifact@v7
      with:
        pattern: test-results_*.tar
    - run: |
        for f in test-results_*/*.tar; do
          tar xvf "$f"
        done
    - run: |
        for f in *.xcresult; do
          python3 ./.github/extract_screenshots_from_xcresult.py "$f" "screenshots/$(basename "$f" .xcresult)"
        done
    - uses: actions/upload-artifact@v7
      with:
        name: screenshots
        path: screenshots